import { v4 as uuid } from "uuid";

export const products = [
  {
    _id: uuid(),
    name: "Cobra 500 Junior Cricket Bat",
    brand: "Gray Nicolls",
    categoryName: "Bats",
    available: 10,
    ratings: 3.5,
    price: 9999,
    prevPrice: 14999,
    badgeText: "",
    inStock: true,
    new: false,
    desc: "",
    imgSrc:
      "https://www.rebelsport.com.au/dw/image/v2/BBRV_PRD/on/demandware.static/-/Sites-srg-internal-master-catalog/default/dw1d96f170/images/59989901/Rebel_59989901_blue_hi-res.jpg?sw=233&sh=233&sm=fit",
  },
  {
    _id: uuid(),
    name: "Cobra 600 Junior Cricket Bat",
    brand: "Gray Nicolls",
    categoryName: "Bats",
    available: 10,
    ratings: 2.5,
    price: 10999,
    prevPrice: 14999,
    badgeText: "",
    inStock: true,
    new: false,
    desc: "",
    imgSrc:
      "https://www.rebelsport.com.au/dw/image/v2/BBRV_PRD/on/demandware.static/-/Sites-srg-internal-master-catalog/default/dw5f3f91ef/images/61405701/Rebel_61405701_orange_hi-res.jpg?sw=233&sh=233&sm=fit",
  },
  {
    _id: uuid(),
    name: "Pace Pro 8.0 Cricket Bat",
    brand: "Kookaburra",
    categoryName: "Bats",
    available: 10,
    ratings: 4.5,
    price: 6999,
    prevPrice: 9999,
    badgeText: "",
    inStock: false,
    new: false,
    desc: "",
    imgSrc:
      "https://www.rebelsport.com.au/dw/image/v2/BBRV_PRD/on/demandware.static/-/Sites-srg-internal-master-catalog/default/dwe57adabb/images/61503201/Rebel_61503201_hi-res.jpg?sw=233&sh=233&sm=fit",
  },
  {
    _id: uuid(),
    name: "Ghost junior 6.0 Cricket Bat",
    brand: "Kookaburra",
    categoryName: "Bats",
    available: 10,
    ratings: 4.5,
    price: 2999,
    prevPrice: 4999,
    badgeText: "New Arrival",
    inStock: true,
    new: true,
    desc: "",
    imgSrc:
      "https://www.rebelsport.com.au/dw/image/v2/BBRV_PRD/on/demandware.static/-/Sites-srg-internal-master-catalog/default/dw697b9ffd/images/61503001/Rebel_61503001_hi-res.jpg?sw=233&sh=233&sm=fit",
  },
  {
    _id: uuid(),
    name: "Kashmir willow",
    brand: "Sunridges",
    categoryName: "Bats",
    available: 10,
    ratings: 4.5,
    price: 2999,
    prevPrice: 4999,
    badgeText: "",
    inStock: false,
    new: false,
    desc: "",
    imgSrc:
      "https://www.rebelsport.com.au/dw/image/v2/BBRV_PRD/on/demandware.static/-/Sites-srg-internal-master-catalog/default/dw4ac7ea05/images/61502601/Rebel_61502601_blue_hi-res.jpg?sw=233&sh=233&sm=fit",
  },
  {
    _id: uuid(),
    name: "Kashmir willow",
    brand: "Sunridges",
    categoryName: "Bats",
    available: 10,
    ratings: 4.5,
    price: 2999,
    prevPrice: 4999,
    badgeText: "",
    inStock: true,
    new: false,
    desc: "",
    imgSrc:
      "https://www.rebelsport.com.au/dw/image/v2/BBRV_PRD/on/demandware.static/-/Sites-srg-internal-master-catalog/default/dw56cd0c80/images/61406001/Rebel_61406001_hi-res.jpg?sw=233&sh=233&sm=fit",
  },
  {
    _id: uuid(),
    name: "Kashmir willow",
    brand: "Sunridges",
    categoryName: "Bats",
    available: 10,
    ratings: 3,
    price: 2999,
    prevPrice: 4999,
    badgeText: "",
    inStock: true,
    new: false,
    desc: "",
    imgSrc:
      "https://www.rebelsport.com.au/dw/image/v2/BBRV_PRD/on/demandware.static/-/Sites-srg-internal-master-catalog/default/dw81ed66a4/images/61409101/Rebel_61409101_hi-res.jpg?sw=233&sh=233&sm=fit",
  },
  {
    _id: uuid(),
    name: "Kashmir willow",
    brand: "Sunridges",
    categoryName: "Bats",
    available: 10,
    ratings: 4.5,
    price: 2999,
    prevPrice: 4999,
    badgeText: "",
    inStock: false,
    new: false,
    desc: "",
    imgSrc:
      "https://www.rebelsport.com.au/dw/image/v2/BBRV_PRD/on/demandware.static/-/Sites-srg-internal-master-catalog/default/dw250bf9dc/images/61502401/Rebel_61502401_white_hi-res.jpg?sw=233&sh=233&sm=fit",
  },
  {
    _id: uuid(),
    name: "Kashmir willow",
    brand: "Sunridges",
    categoryName: "Bats",
    available: 10,
    ratings: 3.5,
    price: 2999,
    prevPrice: 4999,
    badgeText: "",
    inStock: true,
    new: false,
    desc: "",
    imgSrc:
      "https://www.rebelsport.com.au/dw/image/v2/BBRV_PRD/on/demandware.static/-/Sites-srg-internal-master-catalog/default/dwc4eaa2de/images/61502501/Rebel_61502501_green_hi-res.jpg?sw=233&sh=233&sm=fit",
  },
  {
    _id: uuid(),
    name: "Kashmir willow",
    brand: "Sunridges",
    categoryName: "Bats",
    available: 10,
    ratings: 4.5,
    price: 2999,
    prevPrice: 4999,
    badgeText: "",
    inStock: true,
    new: false,
    desc: "",
    imgSrc:
      "https://www.rebelsport.com.au/dw/image/v2/BBRV_PRD/on/demandware.static/-/Sites-srg-internal-master-catalog/default/dw1d48518f/images/61503101/Rebel_61503101_hi-res.jpg?sw=233&sh=233&sm=fit",
  },
  {
    _id: uuid(),
    name: "Retro Beast 8.0 Cricket Bat",
    brand: "Kookaburra",
    categoryName: "Bats",
    available: 10,
    ratings: 5,
    price: 14999,
    prevPrice: 19999,
    badgeText: "Exclusive",
    inStock: true,
    new: false,
    desc: "",
    imgSrc:
      "https://www.rebelsport.com.au/dw/image/v2/BBRV_PRD/on/demandware.static/-/Sites-srg-internal-master-catalog/default/dw7a837021/images/60963901/Rebel_60963901_blue_hi-res.jpg?sw=233&sh=233&sm=fit",
  },
  {
    _id: uuid(),
    name: "NB Pro Season Cricket Bat",
    brand: "New Balance",
    categoryName: "Bats",
    available: 10,
    ratings: 2.5,
    price: 4999,
    prevPrice: 9999,
    badgeText: "",
    inStock: false,
    new: false,
    desc: "",
    imgSrc:
      "https://www.rebelsport.com.au/dw/image/v2/BBRV_PRD/on/demandware.static/-/Sites-srg-internal-master-catalog/default/dw5f3aff30/images/61611801/Rebel_61611801_hi-res.jpg?sw=233&sh=233&sm=fit",
  },
  {
    _id: uuid(),
    name: "SG campus cricket balls",
    brand: "Sunridges",
    categoryName: "Balls",
    available: 10,
    ratings: 4.5,
    price: 499,
    prevPrice: 999,
    badgeText: "New Arrival",
    inStock: false,
    new: true,
    desc: "",
    imgSrc:
      "https://www.rebelsport.com.au/dw/image/v2/BBRV_PRD/on/demandware.static/-/Sites-srg-internal-master-catalog/default/dw848f16cb/images/53036001/Rebel_53036001_hi-res.jpg?sw=233&sh=233&sm=fit",
  },
  {
    _id: uuid(),
    name: "SG campus cricket balls",
    brand: "Sunridges",
    categoryName: "Balls",
    available: 10,
    ratings: 4.5,
    price: 499,
    prevPrice: 999,
    badgeText: "",
    inStock: true,
    new: false,
    desc: "",
    imgSrc:
      "https://www.rebelsport.com.au/dw/image/v2/BBRV_PRD/on/demandware.static/-/Sites-srg-internal-master-catalog/default/dwa708219a/images/53036001/Rebel_53036001-00_hi-res.jpg?sw=233&sh=233&sm=fit",
  },
  {
    _id: uuid(),
    name: "SG campus cricket balls",
    brand: "Sunridges",
    categoryName: "Balls",
    available: 10,
    ratings: 4.5,
    price: 499,
    prevPrice: 999,
    badgeText: "New Arrival",
    inStock: true,
    new: true,
    desc: "",
    imgSrc:
      "https://www.rebelsport.com.au/dw/image/v2/BBRV_PRD/on/demandware.static/-/Sites-srg-internal-master-catalog/default/dwe97b2636/images/58093901/Rebel_58093901_red_hi-res.jpg?sw=233&sh=233&sm=fit",
  },
  {
    _id: uuid(),
    name: "SG campus cricket balls",
    brand: "Sunridges",
    categoryName: "Balls",
    available: 10,
    ratings: 4.5,
    price: 499,
    prevPrice: 999,
    badgeText: "",
    inStock: false,
    new: false,
    desc: "",
    imgSrc:
      "https://www.rebelsport.com.au/dw/image/v2/BBRV_PRD/on/demandware.static/-/Sites-srg-internal-master-catalog/default/dwe97b2636/images/58093901/Rebel_58093901_red_hi-res.jpg?sw=233&sh=233&sm=fit",
  },
  {
    _id: uuid(),
    name: "KK Season cricket balls",
    brand: "Kookaburra",
    categoryName: "Balls",
    available: 10,
    ratings: 4.5,
    price: 499,
    prevPrice: 999,
    badgeText: "New Arrival",
    inStock: true,
    new: true,
    desc: "",
    imgSrc:
      "https://www.rebelsport.com.au/dw/image/v2/BBRV_PRD/on/demandware.static/-/Sites-srg-internal-master-catalog/default/dw57e648d2/images/61502301/Rebel_61502301-00_hi-res.jpg?sw=233&sh=233&sm=fit",
  },
  {
    _id: uuid(),
    name: "KK Season cricket balls",
    brand: "Kookaburra",
    categoryName: "Balls",
    available: 10,
    ratings: 4.5,
    price: 499,
    prevPrice: 999,
    badgeText: "",
    inStock: true,
    new: false,
    desc: "",
    imgSrc:
      "https://www.rebelsport.com.au/dw/image/v2/BBRV_PRD/on/demandware.static/-/Sites-srg-internal-master-catalog/default/dw3cf06413/images/59014601/Rebel_59014601_hi-res.jpg?sw=233&sh=233&sm=fit",
  },
  {
    _id: uuid(),
    name: "Leather cricket balls",
    brand: "Gray Nicolls",
    categoryName: "Balls",
    available: 10,
    ratings: 5.0,
    price: 1899,
    prevPrice: 2999,
    badgeText: "Exclusive",
    inStock: true,
    new: false,
    desc: "",
    imgSrc:
      "https://www.rebelsport.com.au/dw/image/v2/BBRV_PRD/on/demandware.static/-/Sites-srg-internal-master-catalog/default/dw1d7d5b6d/images/58093301/Rebel_58093301_pink_hi-res.jpg?sw=233&sh=233&sm=fit",
  },
  {
    _id: uuid(),
    name: "SG Season cricket balls",
    brand: "Sunridges",
    categoryName: "Balls",
    available: 10,
    ratings: 3.5,
    price: 649,
    prevPrice: 1299,
    badgeText: "",
    inStock: true,
    new: false,
    desc: "",
    imgSrc:
      "https://www.rebelsport.com.au/dw/image/v2/BBRV_PRD/on/demandware.static/-/Sites-srg-internal-master-catalog/default/dwf2be7268/images/61418701/Rebel_61418701_hi-res.jpg?sw=233&sh=233&sm=fit",
  },
  {
    _id: uuid(),
    name: "Duke Season cricket balls",
    brand: "Duke",
    categoryName: "Balls",
    available: 10,
    ratings: 4,
    price: 999,
    prevPrice: 1999,
    badgeText: "",
    inStock: true,
    new: false,
    desc: "",
    imgSrc:
      "https://www.rebelsport.com.au/dw/image/v2/BBRV_PRD/on/demandware.static/-/Sites-srg-internal-master-catalog/default/dw92e67b00/images/58093201/Rebel_58093201_white_hi-res.jpg?sw=233&sh=233&sm=fit",
  },
  {
    _id: uuid(),
    name: "KK Season cricket balls",
    brand: "Kookaburra",
    categoryName: "Balls",
    available: 10,
    ratings: 4.5,
    price: 499,
    prevPrice: 999,
    badgeText: "New Arrival",
    inStock: true,
    new: true,
    desc: "",
    imgSrc:
      "https://www.rebelsport.com.au/dw/image/v2/BBRV_PRD/on/demandware.static/-/Sites-srg-internal-master-catalog/default/dwd6f612f8/images/58093401/Rebel_58093401_red_hi-res.jpg?sw=233&sh=233&sm=fit",
  },
  {
    _id: uuid(),
    name: "Asics runners",
    brand: "Asics",
    categoryName: "Shoes",
    available: 10,
    ratings: 4.5,
    price: 2999,
    prevPrice: 4999,
    badgeText: "",
    inStock: true,
    new: false,
    desc: "",
    imgSrc:
      "https://www.rebelsport.com.au/dw/image/v2/BBRV_PRD/on/demandware.static/-/Sites-srg-internal-master-catalog/default/dw2accb3e3/images/61503501/Rebel_61503501_whitelime_hi-res.jpg?sw=233&sh=233&sm=fit",
  },
  {
    _id: uuid(),
    name: "Puma Rubber shoes",
    brand: "Puma",
    categoryName: "Shoes",
    available: 10,
    ratings: 4.5,
    price: 1499,
    prevPrice: 2999,
    badgeText: "",
    inStock: true,
    new: false,
    desc: "",
    imgSrc:
      "https://www.rebelsport.com.au/dw/image/v2/BBRV_PRD/on/demandware.static/-/Sites-srg-internal-master-catalog/default/dwae47e099/images/61503501/Rebel_61503501-00_whitelime_hi-res.jpg?sw=233&sh=233&sm=fit",
  },
  {
    _id: uuid(),
    name: "Adidas Stealth",
    brand: "Adidas",
    categoryName: "Shoes",
    available: 10,
    ratings: 2.5,
    price: 2999,
    prevPrice: 4999,
    badgeText: "",
    inStock: false,
    new: false,
    desc: "",
    imgSrc:
      "https://www.rebelsport.com.au/dw/image/v2/BBRV_PRD/on/demandware.static/-/Sites-srg-internal-master-catalog/default/dwe7345ae5/images/58076101/Rebel_58076101_whiteblue_hi-res.jpg?sw=233&sh=233&sm=fit",
  },
  {
    _id: uuid(),
    name: "Puma Rubber shoes",
    brand: "Puma",
    categoryName: "Shoes",
    available: 10,
    ratings: 3.5,
    price: 2999,
    prevPrice: 4999,
    badgeText: "",
    inStock: true,
    new: false,
    desc: "",
    imgSrc:
      "https://www.rebelsport.com.au/dw/image/v2/BBRV_PRD/on/demandware.static/-/Sites-srg-internal-master-catalog/default/dw6ef691ed/images/59591401/Rebel_59591401_white_hi-res.jpg?sw=233&sh=233&sm=fit",
  },
  {
    _id: uuid(),
    name: "Puma Rubber shoes",
    brand: "Puma",
    categoryName: "Shoes",
    available: 10,
    ratings: 4.5,
    price: 2999,
    prevPrice: 4999,
    badgeText: "",
    inStock: true,
    new: false,
    desc: "",
    imgSrc:
      "https://www.rebelsport.com.au/dw/image/v2/BBRV_PRD/on/demandware.static/-/Sites-srg-internal-master-catalog/default/dwa50dfeda/images/59591401/Rebel_59591401-00_white_hi-res.jpg?sw=233&sh=233&sm=fit",
  },
  {
    _id: uuid(),
    name: "Puma Rubber shoes",
    brand: "Puma",
    categoryName: "Shoes",
    available: 10,
    ratings: 4.5,
    price: 2999,
    prevPrice: 4999,
    badgeText: "",
    inStock: true,
    new: false,
    desc: "",
    imgSrc:
      "https://www.rebelsport.com.au/dw/image/v2/BBRV_PRD/on/demandware.static/-/Sites-srg-internal-master-catalog/default/dw33c5fbf1/images/61680501/Rebel_61680501_whiteblue_hi-res.jpg?sw=233&sh=233&sm=fit",
  },
  {
    _id: uuid(),
    name: "Asics High flyers",
    brand: "Asics",
    categoryName: "Shoes",
    available: 10,
    ratings: 4.5,
    price: 2999,
    prevPrice: 4999,
    badgeText: "",
    inStock: false,
    new: false,
    desc: "",
    imgSrc:
      "https://www.rebelsport.com.au/dw/image/v2/BBRV_PRD/on/demandware.static/-/Sites-srg-internal-master-catalog/default/dw50c96f6a/images/61680501/Rebel_61680501-00_whiteblue_hi-res.jpg?sw=233&sh=233&sm=fit",
  },
  {
    _id: uuid(),
    name: "Puma Rubber shoes",
    brand: "Puma",
    categoryName: "Shoes",
    available: 10,
    ratings: 5,
    price: 2999,
    prevPrice: 4999,
    badgeText: "",
    inStock: true,
    new: false,
    desc: "",
    imgSrc:
      "https://www.rebelsport.com.au/dw/image/v2/BBRV_PRD/on/demandware.static/-/Sites-srg-internal-master-catalog/default/dw21fe01a9/images/61680601/Rebel_61680601_whitegold_hi-res.jpg?sw=233&sh=233&sm=fit",
  },
  {
    _id: uuid(),
    name: "Puma Rubber shoes",
    brand: "Puma",
    categoryName: "Shoes",
    available: 10,
    ratings: 4.5,
    price: 2999,
    prevPrice: 4999,
    badgeText: "",
    inStock: true,
    new: false,
    desc: "",
    imgSrc:
      "https://www.rebelsport.com.au/dw/image/v2/BBRV_PRD/on/demandware.static/-/Sites-srg-internal-master-catalog/default/dwcf060f0c/images/61680601/Rebel_61680601-00_whitegold_hi-res.jpg?sw=233&sh=233&sm=fit",
  },
  {
    _id: uuid(),
    name: "Reebok Runners",
    brand: "Reebok",
    categoryName: "Shoes",
    available: 10,
    ratings: 3.0,
    price: 4999,
    prevPrice: 6999,
    badgeText: "",
    inStock: true,
    new: false,
    desc: "",
    imgSrc:
      "https://www.rebelsport.com.au/dw/image/v2/BBRV_PRD/on/demandware.static/-/Sites-srg-internal-master-catalog/default/dwad9d7c3d/images/61503301/Rebel_61503301_whitelime_hi-res.jpg?sw=233&sh=233&sm=fit",
  },
  {
    _id: uuid(),
    name: "Puma Rubber shoes",
    brand: "Puma",
    categoryName: "Shoes",
    available: 10,
    ratings: 4.5,
    price: 2999,
    prevPrice: 4999,
    badgeText: "",
    inStock: false,
    new: false,
    desc: "",
    imgSrc:
      "https://www.rebelsport.com.au/dw/image/v2/BBRV_PRD/on/demandware.static/-/Sites-srg-internal-master-catalog/default/dw3cfa1e05/images/61503301/Rebel_61503301-00_whitelime_hi-res.jpg?sw=233&sh=233&sm=fit",
  },
  {
    _id: uuid(),
    name: "Adidas Rubber shoes",
    brand: "Adidas",
    categoryName: "Shoes",
    available: 10,
    ratings: 3.5,
    price: 2999,
    prevPrice: 4999,
    badgeText: "New Arrival",
    inStock: true,
    new: true,
    desc: "",
    imgSrc:
      "https://www.rebelsport.com.au/dw/image/v2/BBRV_PRD/on/demandware.static/-/Sites-srg-internal-master-catalog/default/dwdd06fbdf/images/61503401/Rebel_61503401_whitelime_hi-res.jpg?sw=233&sh=233&sm=fit",
  },
  {
    _id: uuid(),
    name: "Asics Spikes",
    brand: "Asics",
    categoryName: "Shoes",
    available: 10,
    ratings: 4.5,
    price: 1599,
    prevPrice: 2999,
    badgeText: "",
    inStock: true,
    new: false,
    desc: "",
    imgSrc:
      "https://www.rebelsport.com.au/dw/image/v2/BBRV_PRD/on/demandware.static/-/Sites-srg-internal-master-catalog/default/dwd480b108/images/61616101/Rebel_61616101_whiteblack_hi-res.jpg?sw=233&sh=233&sm=fit",
  },
];
